backend: 
  name: git-gateway
  branch: main
  identity_url: https://fancy-cendol-7d2238.netlify.app
  accept_roles: ["admin"]

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", default: ["blog"] }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
